# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Attila's lab notebook
email: attila.gulyas.kovacs@gmail.com
description: > # this means to ignore newlines until "baseurl:"
    research in the Chess lab
baseurl: "/~attila" # the subpath of your site, e.g. /blog
url: "http://127.0.0.1:4000" # the base hostname & protocol for your site
twitter_username: 
github_username:  attilagk

# Build settings
markdown: kramdown
theme: jekyll-theme-dinky
#theme: minima

gems: [jekyll-paginate, jekyll/scholar]

paginate: 10

future: TRUE
permalink: /:year-:month-:day-:title.html
# Google analytics tracking ID; see article below
# https://desiredpersona.com/google-analytics-jekyll/
google_analytics: UA-112433885-1
